### ISSUE TITLE
message.answer instead of vk.api_request

### ISSUE THREAD

**Issue by prostomarkeloff** [DarklyZ/VkLvlExp#3]
В `message.answer` тоже можно передавать разные аргументы, например sticker_id, или disable_mentions

**Comment by DarklyZ** [comment]
Хорошо, сейчас исправлю. Можно такой вопрос? Почему в Attachment нету аттрибута wall?

**Comment by prostomarkeloff** [comment]
> Хорошо, сейчас исправлю. Можно такой вопрос? Почему в Attachment нету аттрибута wall?

Хмм, возможно упустили из виду, можно в принципе добавить.

**Comment by DarklyZ** [comment]
Это хорошо, а то уже сделал вилку и хотел сам попробовать добавить)

**Comment by DarklyZ** [comment]
@prostomarkeloff, и ещё в базовой модели Sticker аттрибут должен быть не id, а sticker_id
