### ISSUE TITLE
Предложение по рефакторингу кода

### ISSUE THREAD

**Issue by timoniq** [DarklyZ/VkLvlExp#4]
Предлагаю обновить код до более новой версии vkbottle, а именно `2.7.1` по причине большого количества улучшений, позволяющих улучшить качество этого проекта

**Comment by DarklyZ** [comment]
Хорошо, обновил либу, поменял 1 импорт. Это всё или что-то ещё надо?

**Comment by timoniq** [comment]
ура! 🏩
